const ActionTypes = {
  INITIALIZE: 'CART_INITIALIZE',
  REVERT: 'CART_REVERT',
  ADD_ITEM: 'CART_ADD_ITEM',
  REMOVE_ITEM: 'CART_REMOVE_ITEM',
  UPDATE_ITEM: 'CART_UPDATE_ITEM',
  RESET: 'CART_RESET'
};

export default ActionTypes;
