const ActionTypes = {
  INITIALIZE: 'CART_INITIALIZE',
  EMPTY: 'CART_EMPTY',
  ADD_ITEM: 'CART_ADD_ITEM',
  REMOVE_ITEM: 'CART_REMOVE_ITEM',
  UPDATE_ITEM: 'CART_UPDATE_ITEM',
  RESET: 'CART_RESET',
  INSERT_ARTICLE: 'CART_INSERT_ARTICLE'
};

export default ActionTypes;
